### ISSUE TITLE
some users receive duplicate infections in memes_infections_XX.log files

### ISSUE THREAD

**Issue by teminndtx** [dovedevic/memonavirus#5]
looking through the log files, it looks like several users receive the infection more than once. for example, user 'u/blep0w0' shows up in the 'infected user' field 46 times. is this expected behavior?

**Comment by dovedevic** [comment]
This may have been solved with #4. Could you reverify please?

**Comment by dovedevic** [comment]
Fixed with #8

**Comment by teminndtx** [comment]
Thanks! Just checking now and all looks good.
