### ISSUE TITLE
some users spread infection before receiving the infection

### ISSUE THREAD

**Issue by teminndtx** [dovedevic/memonavirus#6]
based on the log files, it looks like some users appear as a "cause user" prior to showing up as an "infected user" -- aka spreading the virus before receiving the virus.

for example, 'u/GarageInc' infects user 'u/HeyJamesIsGay' on 2020-03-21, but does not receive an infection until 2020-04-12 from user 'u/FestiveKillian'

similarly, some users show up as "cause user" without EVER showing up as an "infected user", for example 'u/GarageInc' infects 7 other users without showing up as the 'infected user' in any logs.

**Comment by dovedevic** [comment]
#4 identifies all roots of invalid trees, we're looking into options on how to merge this forest into the main tree.

**Comment by dovedevic** [comment]
Fixed with #8. Everything you need should be in data/clean.

**Comment by teminndtx** [comment]
Thanks! Just checking now and all looks good.
